{
 "title": "ElasticGrid Task Groups Status",
 "tags": [ "nomad" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Nomad Task Groups Starting",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_job]]/[[tag_task_group]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "task_group" ], "type": "tag" },
      { "params": [ "job" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "nomad_nomad_job_summary_starting",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "gauge", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Starting NOW",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "nomad_nomad_job_summary_starting",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nomad Task Groups Queued",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_job]]/[[tag_task_group]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "task_group" ], "type": "tag" },
      { "params": [ "job" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "nomad_nomad_job_summary_queued",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "gauge", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Queued NOW",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "nomad_nomad_job_summary_queued",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nomad Task groups Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_job]]/[[tag_task_group]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "job" ], "type": "tag" },
      { "params": [ "task_group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_nomad_job_summary_failed",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "nomad_nomad_job_summary_failed",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  }
 ]
}